name: DEPLOYMENT

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/github/**'
      - './README.md'
      - './.pages.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # 构建
      - name: Export .env File
        run: pnpm build-env
        env:
          BLOG_CHANGELOG_WINCLIENT_ZH_ID: ${{ vars.BLOG_CHANGELOG_WINCLIENT_ZH_ID }}
          BLOG_CHANGELOG_WINCLIENT_EN_ID: ${{ vars.BLOG_CHANGELOG_WINCLIENT_EN_ID }}
          BLOG_CHANGELOG_WINCLIENT_JA_ID: ${{ vars.BLOG_CHANGELOG_WINCLIENT_JA_ID }}
          BLOG_CHANGELOG_WEB_ZH_ID: ${{ vars.BLOG_CHANGELOG_WEB_ZH_ID }}
          BLOG_CHANGELOG_WEB_EN_ID: ${{ vars.BLOG_CHANGELOG_WEB_EN_ID }}
          BLOG_CHANGELOG_WEB_JA_ID: ${{ vars.BLOG_CHANGELOG_WEB_JA_ID }}

      - name: Refresh Members Data
        run: pnpm build-member
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}

      - name: Refresh Blog Data
        run: pnpm build-blog
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}

      - name: Build Site
        run: pnpm build-vitepress

      - name: Build lunaria
        run: pnpm lunaria:build

      # 部署
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          # 删除服务器上目录里所有文件
          # ARGS: '-avz --delete'
          # 项目 build 后静态文件位置
          SOURCE: './dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
